name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: dayan/php

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      run: |
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
      
    - name: Docker Push
      run: docker push $IMAGE_NAME
